// SPDX-FileCopyrightText: 2025 NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: AGPL-3.0-or-later
/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TravelTimesLevel, TravelTimesVehicleType } from "./data/travel-times/TravelTimesShort";
import { ViewLayout } from "./data/breakpoints";
import { IconName } from "./blocks/icon/icon.component";
export { TravelTimesLevel, TravelTimesVehicleType } from "./data/travel-times/TravelTimesShort";
export { ViewLayout } from "./data/breakpoints";
export { IconName } from "./blocks/icon/icon.component";
export namespace Components {
    /**
     * Traffic forecast component
     */
    interface NoiA22TravelTimes {
        /**
          * Language
         */
        "language": string;
        /**
          * Layout appearance
         */
        "layout": ViewLayout;
        /**
          * Reload traffic data
         */
        "refreshData": () => Promise<void>;
        /**
          * Data reload interval
         */
        "reloadInterval": number;
        /**
          * Vehicle type
         */
        "vehicleType": TravelTimesVehicleType;
    }
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface NoiIcon {
        /**
          * icon name
         */
        "name": IconName | string;
    }
    /**
     * (INTERNAL) render a toggle control.
     */
    interface NoiToggle {
        /**
          * Checked state
         */
        "checked": boolean;
        /**
          * Toggle checked state
         */
        "toggleValue": () => Promise<void>;
    }
    /**
     * (INTERNAL) part of 'noi-traffic-prediction'
     */
    interface NoiTrafficLevelBox {
        "level": TravelTimesLevel | string;
    }
}
export interface NoiToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiToggleElement;
}
declare global {
    /**
     * Traffic forecast component
     */
    interface HTMLNoiA22TravelTimesElement extends Components.NoiA22TravelTimes, HTMLStencilElement {
    }
    var HTMLNoiA22TravelTimesElement: {
        prototype: HTMLNoiA22TravelTimesElement;
        new (): HTMLNoiA22TravelTimesElement;
    };
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface HTMLNoiIconElement extends Components.NoiIcon, HTMLStencilElement {
    }
    var HTMLNoiIconElement: {
        prototype: HTMLNoiIconElement;
        new (): HTMLNoiIconElement;
    };
    interface HTMLNoiToggleElementEventMap {
        "noiChange": { checked: boolean };
    }
    /**
     * (INTERNAL) render a toggle control.
     */
    interface HTMLNoiToggleElement extends Components.NoiToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiToggleElementEventMap>(type: K, listener: (this: HTMLNoiToggleElement, ev: NoiToggleCustomEvent<HTMLNoiToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiToggleElementEventMap>(type: K, listener: (this: HTMLNoiToggleElement, ev: NoiToggleCustomEvent<HTMLNoiToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiToggleElement: {
        prototype: HTMLNoiToggleElement;
        new (): HTMLNoiToggleElement;
    };
    /**
     * (INTERNAL) part of 'noi-traffic-prediction'
     */
    interface HTMLNoiTrafficLevelBoxElement extends Components.NoiTrafficLevelBox, HTMLStencilElement {
    }
    var HTMLNoiTrafficLevelBoxElement: {
        prototype: HTMLNoiTrafficLevelBoxElement;
        new (): HTMLNoiTrafficLevelBoxElement;
    };
    interface HTMLElementTagNameMap {
        "noi-a22-travel-times": HTMLNoiA22TravelTimesElement;
        "noi-icon": HTMLNoiIconElement;
        "noi-toggle": HTMLNoiToggleElement;
        "noi-traffic-level-box": HTMLNoiTrafficLevelBoxElement;
    }
}
declare namespace LocalJSX {
    /**
     * Traffic forecast component
     */
    interface NoiA22TravelTimes {
        /**
          * Language
         */
        "language"?: string;
        /**
          * Layout appearance
         */
        "layout"?: ViewLayout;
        /**
          * Data reload interval
         */
        "reloadInterval"?: number;
        /**
          * Vehicle type
         */
        "vehicleType"?: TravelTimesVehicleType;
    }
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface NoiIcon {
        /**
          * icon name
         */
        "name"?: IconName | string;
    }
    /**
     * (INTERNAL) render a toggle control.
     */
    interface NoiToggle {
        /**
          * Checked state
         */
        "checked"?: boolean;
        /**
          * Emitted when checked value is changed by user click
         */
        "onNoiChange"?: (event: NoiToggleCustomEvent<{ checked: boolean }>) => void;
    }
    /**
     * (INTERNAL) part of 'noi-traffic-prediction'
     */
    interface NoiTrafficLevelBox {
        "level"?: TravelTimesLevel | string;
    }
    interface IntrinsicElements {
        "noi-a22-travel-times": NoiA22TravelTimes;
        "noi-icon": NoiIcon;
        "noi-toggle": NoiToggle;
        "noi-traffic-level-box": NoiTrafficLevelBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Traffic forecast component
             */
            "noi-a22-travel-times": LocalJSX.NoiA22TravelTimes & JSXBase.HTMLAttributes<HTMLNoiA22TravelTimesElement>;
            /**
             * (INTERNAL) render an icon.
             * Icons are embedded inside the component (so far).
             * Icon size can be changed by 'font-size' style
             */
            "noi-icon": LocalJSX.NoiIcon & JSXBase.HTMLAttributes<HTMLNoiIconElement>;
            /**
             * (INTERNAL) render a toggle control.
             */
            "noi-toggle": LocalJSX.NoiToggle & JSXBase.HTMLAttributes<HTMLNoiToggleElement>;
            /**
             * (INTERNAL) part of 'noi-traffic-prediction'
             */
            "noi-traffic-level-box": LocalJSX.NoiTrafficLevelBox & JSXBase.HTMLAttributes<HTMLNoiTrafficLevelBoxElement>;
        }
    }
}
